"""Remove unused tables and fields - database cleanup

Revision ID: 0c704dd026d0
Revises: 6d8044164f8a
Create Date: 2025-12-03 23:38:25.809738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c704dd026d0'
down_revision: Union[str, None] = '6d8044164f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_checklists_customer_name'), table_name='customer_checklists')
    op.drop_index(op.f('ix_customer_checklists_id'), table_name='customer_checklists')
    op.drop_table('customer_checklists')
    op.drop_index(op.f('ix_salesforce_sync_id'), table_name='salesforce_sync')
    op.drop_table('salesforce_sync')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_column('audio_files', 'duration_seconds')
    op.drop_column('checklist_categories', 'default_weight')
    op.drop_column('checklist_categories', 'max_score')
    op.drop_column('checklist_items', 'key_mindset')
    op.drop_column('checklist_items', 'weight')
    op.drop_column('checklist_items', 'points')
    op.drop_constraint(op.f('organizations_domain_key'), 'organizations', type_='unique')
    op.drop_column('organizations', 'domain')
    op.drop_column('organizations', 'scoring_mode')
    op.drop_column('organizations', 'max_users')
    op.drop_column('scoring_results', 'previous_score')
    op.drop_column('scoring_results', 'score_change')
    op.alter_column('session_responses', 'was_changed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('session_responses', 'changed_at')
    op.drop_column('sessions', 'sync_attempted_at')
    op.drop_column('sessions', 'is_synced')
    op.drop_column('teams', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('is_synced', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('sync_attempted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('session_responses', sa.Column('changed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('session_responses', 'was_changed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('scoring_results', sa.Column('score_change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('scoring_results', sa.Column('previous_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('max_users', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('scoring_mode', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('domain', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('organizations_domain_key'), 'organizations', ['domain'], postgresql_nulls_not_distinct=False)
    op.add_column('checklist_items', sa.Column('points', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('checklist_items', sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('checklist_items', sa.Column('key_mindset', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('checklist_categories', sa.Column('max_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('checklist_categories', sa.Column('default_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('audio_files', sa.Column('duration_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('changes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('audit_logs_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('salesforce_sync',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('salesforce_object_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('salesforce_object_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_synced', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sync_error', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('fields_synced', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('salesforce_sync_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('salesforce_sync_pkey'))
    )
    op.create_index(op.f('ix_salesforce_sync_id'), 'salesforce_sync', ['id'], unique=False)
    op.create_table('customer_checklists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('opportunity_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('items_completed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score_change', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('items_improved', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('items_declined', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deal_stage', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('customer_checklists_session_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('customer_checklists_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('customer_checklists_pkey'))
    )
    op.create_index(op.f('ix_customer_checklists_id'), 'customer_checklists', ['id'], unique=False)
    op.create_index(op.f('ix_customer_checklists_customer_name'), 'customer_checklists', ['customer_name'], unique=False)
    # ### end Alembic commands ###
